# Site settings
title: Endless Summertime
header-img: "img/elephant.jpg"
tagline: "企鹅睡觉的地方"  
description: " Summer is a dreamy season."  
baseurl: ""
url: "http://summerpenguin.me"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "SummerPenguin"
  email: zhzhzol@hotmail.com
  bio: "至此不渝"

# Data
gavatar: img/penguin2.ico
favicon: img/penguin2.ico


github_username: summerpenguin 


# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: SummerPenguin/Shenzhen

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "SummerPenguin"
      header-img: "img/summer.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : SummerPenguin
  disqus :
      short_name : SummerPenguin

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation